// <autogenerated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameStore.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddIdToOrderGame : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_UserBans",
                table: "UserBans");

            migrationBuilder.DropPrimaryKey(
                name: "PK_OrderGame",
                table: "OrderGame");

            migrationBuilder.DropColumn(
                name: "UserName",
                table: "UserBans");

            migrationBuilder.AddColumn<Guid>(
                name: "UserId",
                table: "UserBans",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "Id",
                table: "OrderGame",
                type: "uniqueidentifier",
                nullable: true);
            
            migrationBuilder.Sql(
                @"UPDATE OrderGame SET Id = NEWID() WHERE Id IS NULL");
            
            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                table: "OrderGame",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserBans",
                table: "UserBans",
                columns: new[] { "UserId", "BannedUntil" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_OrderGame",
                table: "OrderGame",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_OrderGame_OrderId",
                table: "OrderGame",
                column: "OrderId");

            migrationBuilder.AddForeignKey(
                name: "FK_UserBans_AspNetUsers_UserId",
                table: "UserBans",
                column: "UserId",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserBans_AspNetUsers_UserId",
                table: "UserBans");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserBans",
                table: "UserBans");

            migrationBuilder.DropPrimaryKey(
                name: "PK_OrderGame",
                table: "OrderGame");

            migrationBuilder.DropIndex(
                name: "IX_OrderGame_OrderId",
                table: "OrderGame");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "UserBans");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "OrderGame");

            migrationBuilder.AddColumn<string>(
                name: "UserName",
                table: "UserBans",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserBans",
                table: "UserBans",
                columns: new[] { "UserName", "BannedUntil" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_OrderGame",
                table: "OrderGame",
                columns: new[] { "OrderId", "ProductId" });
        }
    }
}
